name: 'my_project'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store ephemeral artifacts
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
